### ISSUE TITLE
Reshaping BlockArray may reorder axes for certain block shapes

### ISSUE THREAD

**Issue by dlzou** [nums-project/nums#35]
Test script reproducing this issue can be found on the team Slack.

**Comment by elibol** [comment]
This can be reproduced easily with
```
arr = app_inst.random_state(1337).random((2, 2), (1, 2))
arr_np = arr.get()
arr = arr.reshape(block_shape=(2, 1))
assert np.allclose(arr_np, arr.get())
```

Where `app_inst` is an instance of `ArrayApplication`.

The issue is due to an optimized reshape routine which accepts operations that are not actually supported. The fix is to either remove this reshape routine, or restrict the set of problems it accepts. In the latter case, tests need to be updated to cover the new set of reshape problems.

The routine and its acceptance test can be found here: https://github.com/nums-project/nums/blob/master/nums/core/array/blockarray.py#L830-L859
